#%RAML 1.0 NamedExample
value:
-
    ID: 1
    name: patrick
    firstname: juvet
    birth: 2023-06-14T10:30:00Z
-
    ID: 2
    name: hedmont
    firstname: cyril
    birth: 2023-06-14T10:30:00Z
-
    ID: 3
    name: ratcha
    firstname: greg
    birth: 2023-06-14T10:30:00Z
-
    ID: 4
    name: piron
    firstname: bastien
    birth: 2023-06-14T10:30:00Z